# install.packages("remotes")
remotes::install_github("uyedaj/treeplyr", upgrade = "never")
remotes::install_github("phenoscape/rphenoscape", upgrade = "never")
remotes::install_github("uyedaj/rphenoscate", upgrade = "never")
install.packages("Revticulate")
usethis::edit_r_environ()
library(rphenoscape)
library(rphenoscate)
library(Revticulate)
T <- initQ(c("T*", "T"), 1)
A <- initQ(c("A*", "A"), 1)
C <- initQ(c("r", "b"), 1)
Qarmor <- amaED(A, C, type = "ql")
Qta <- amaED(T, Qarmor, type = "ap")
rownames(Qta)
cat(as_matrixRB(Qta))
doRev(source('d:/data/ms/Lorentz-Workshop/book/day2/tail-armor.Rev'))


library(ape)
plot(read.nexus("output/tail-armor.consensus.tre"))